// <auto-generated />
namespace Finance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update200318 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update200318));
        
        string IMigrationMetadata.Id
        {
            get { return "201803201415560_update20.03.18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
